version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/rails_app/'
    ports:
      - '3011:3011'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3312:3312'
