version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  external_authentication:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/external_authentication/'
    ports:
      - '3013:3013'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3314:3314'
